[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "stochastic-rs"
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = ["numpy"]

[tool.maturin]
features = ["python"]
